language: python
python:
  - "3.6"
  - "3.7"
cache: pip
before_install:
  - sudo apt-get -y install lib libsystemd-dev libdbus-glib-1-dev libdbus-1-dev
install:
  - pip install -r requirements.txt
script:
  - python -m unittest discover -s app/tests -t app/